### PR TITLE
feat: Throw Error When Connecting Wallet

### PR DESCRIPTION
**Pull request by JoseRFelix**
## Description

Throw errors coming from the `connect` wallet method. This will be useful to create predictable UI states while connecting a wallet.

### CODE REVIEW

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by pyramation** [comment]
I think it does make sense to throw errors, @liujun93 will this break anything?

**Comment by JoseRFelix** [comment]
@liujun93 I need to manage errors within a function by using the `catch` method/operator, rather than depending on side effects, for our bridge experience. It's less error-prone and makes the UI predictable. I don't believe this is a breaking change. These errors will be thrown globally if not caught by a `catch`.

**Comment by liujun93** [comment]
@JoseRFelix Just published a new version and added `throwErrors` option. You can set `throwErrors` to be `true` in your dapp.  https://docs.cosmoskit.com/provider/chain-provider#throwerrors

**Comment by pyramation** [comment]
Should we breathe new life into this issue? cc @JoseRFelix

**Pull request closed without merging**
