### PR TITLE
Interactive dApp Iframe Passthrough

### PR DESCRIPTION
**Pull request by NoahSaso**
## What is this?

Gnosis Safe has a library of dApps and an iframe-based viewer that allows seamless integration between dApps and smart contract accounts. This makes it extremely easy and intuitive for the user to interact with their Gnosis Safe account, as well as other dApps in the ecosystem, from one place.

The Cosmos is currently lacking a similar ease of interaction between users and dApps, as well as dApps and dApps. Osmosis, in building its Osmosis App Store, is poised to bring this missing cohesion to the Cosmos ecosystem. In order to accomplish this, a standardized wallet adapter library run by all dApps—Cosmos Kit—must support this iframe passthrough functionality.

This feature aims bring this critical iframe passthrough functionality into Cosmos Kit such that all dApps in the Cosmos ecosystem automatically support embedding after an upgrade. This will be very useful for the Osmosis App Store to become a host of trusted dApps.

It is also built so the parent dApp that's controlling the iframe can manually handle the signed transactions. For example, DAO DAO wants to show an in-app browser and make proposals based on transactions. This way, DAOs can natively interact with dApps without the dApp needing to do any custom work.

## Attribution

Thanks to @pyramation for connecting me with the Osmosis Grants Program and Osmosis Grants Program for funding a grant to get this built!

## How does it work?

This adds an `iframe` wallet built into the `core` package that is automatically added to the beginning of the wallet list when it detects that it is running inside of an iframe (i.e. not the `window.top` window). It is disable-able with `disableIframe`. It will also try to auto-connect to the iframe wallet on mount instead of the saved wallet, and it prevents saving the iframe wallet as the connected wallet to not override other saved wallets. This is so that it does not interfere with the user interacting with the site directly on their own.

The `useIframe` hook used in the parent frame establishes the communication channel between the two Cosmos Kit instances, setting up event listeners and passing messages from the `iframe` wallet running inside the iframe to the wallet client connected in the parent window. An example can be seen in `iframe.tsx` and `iframe-alert.tsx` in the example package. Essentially, `useIframe` returns an iframe ref that must be attached to the iframe element.

### CODE REVIEW

**Comment by liujun93** [comment]
@NoahSaso Can you also add docs here? suppose to include `ChainProvider` props and `Hooks`

**Comment by liujun93** [comment]
Issue I found when trying to use it.

1. connect a wallet in dApp (i.e. Leap)
2. connect `Iframe Parent` in iframe
3. disconnect in iframe
4. reopen the modal in iframe

the first wallet becomes the parent wallet Leap rather than the button `Iframe Parent`.

**Comment by NoahSaso** [comment]
> Issue I found when trying to use it.
> 
> 1. connect a wallet in dApp (i.e. Leap)
> 2. connect `Iframe Parent` in iframe
> 3. disconnect in iframe
> 4. reopen the modal in iframe
> 
> the first wallet becomes the parent wallet Leap rather than the button `Iframe Parent`.

Yeah it's supposed to show the name of the parent connected wallet in the iframe. I don't quite understand the bug, can you take a video?

**Comment by liujun93** [comment]
@NoahSaso this is the video link. https://streamable.com/7fuuvb

**Comment by NoahSaso** [comment]
> @NoahSaso this is the video link. https://streamable.com/7fuuvb

Ah great thank you. Yeah it's supposed to show the parent wallet in the iframe, so the Leap is correct, though it should probably say '(parent)' to be more clear. The issue is that it's not detecting when the parent connects. If you connect and then load the iframe, it'll auto connect, but since the iframe is loaded first here, it's not detecting the connection. I will fix this later this week.

**Comment by NoahSaso** [comment]
@liujun93 opened a new PR to fix this behavior: https://github.com/cosmology-tech/cosmos-kit/pull/330

**Pull request merged**
