### PR TITLE
Resolve Stargaze Names

### PR DESCRIPTION
**Pull request by 0xArbi**
#### Overview

Basic attempt at rendering a `.stars` domain in place of a users "wallet username" if they have one.

#### Notes

- IMO it's pretty uncommon that wallets actually expose a "username" to dapps. MetaMask, WalletConnect, etc all do not support this, seems to be a Keplr implementation detail
- This approach is nice because consumers don't have to change anything to start having this data come through. Another way would be introducing another field on the cosmos-kit API like `stargazeName` so consumers can do `stargazeName ?? username` 
- Next step would be to bubble up the image associated with the name NFT, if the user has set one

### CODE REVIEW

**Review by shanev — APPROVED** [review]
LGTM LFG

**Comment by pyramation** [comment]
hey @0xArbi appreciate this! 

I notice this is in the core? Can we make a separate package? 

I think the proper way is similar to how we managed wallets, and create an adapter. Also some folks may not use name services in their apps and this type of feature makes sense to make as a plugin.

**Comment by pyramation** [comment]
upon second review, maybe we allow developers to pass in `nameResolvers: () -> Promise<string>` as an async function — so the adapter would be overkill. This can be quite simple and we have an optional parameter for the provider.

**Comment by 0xArbi** [comment]
@pyramation I've pushed up some changes

- adding a new `@cosmos-kit/name-resolvers` package
- letting people choose a name resolver to inject into the provider (most people will use the `defaultNameResolver`)

Let me know what you think!

**Comment by pyramation** [comment]
awesome! thanks @0xArbi :) 

This looks solid — in general the idea is to keep core pure and everything is extension/plugin with packages. I think what you did looks great, but will need June to do a review. We're just on the brink of finish our sprint for wallet connect v2 — will have team review and merge this ASAP!

**Pull request merged**
