### PR TITLE
feat: Add Tailwind Wallet CosmosKit adapter

### PR DESCRIPTION
**Pull request by baoskee**
Tailwind is a Cosmos wallet that lets users pay gas in any token on any chain. We just launched our public beta last week. See [website](https://tailwind.zone) and Chrome [extension](https://chromewebstore.google.com/detail/tailwind-wallet/dpnfollacokcbkeiidhplhjpafkbfacj?hl=en&authuser=0). You can use code `USE-COSMOSKIT` to test the wallet.

store

### CODE REVIEW

**Comment by twhy** [comment]
@baoskee  Please don't put all the code in one `index.ts`.  Put them in different files just like other wallets.

**Comment by baoskee** [comment]
> @baoskee Please don't put all the code in one `index.ts`. Put them in different files just like other wallets.

Just did in last commit. Lmk what you think

**Comment by twhy** [comment]
@baoskee Please create another PR to add these things.
1. Add a tailwind package which exports tailwind-extension
2. Add docs
3. Add tailwind to `cosmos-kit` package
You can use this PR as reference, thanks.
https://github.com/cosmology-tech/cosmos-kit/pull/408
@pyramation  FYI

**Comment by thisispalash** [comment]
@twhy opened a PR ~ https://github.com/cosmology-tech/cosmos-kit/pull/415

**Pull request merged**
