### PR TITLE
Feature/cosmostation mobile inject

### PR DESCRIPTION
**Pull request by soaryong-c**

### CODE REVIEW

**Comment by twhy** [comment]
Hi @soaryong-c, can you explain a bit why you removed the `wallet-connect` folder ?
And what are the differences between `@cosmos-kit/cosmostation-extension` and the `extension` folder you added in `@cosmos-kit/cosmostation-mobile` ?

**Comment by soaryong-c** [comment]
@twhy 
This pr is in draft state.
I have requested a review from @liujun93.

The reason for removing wallet-connect is that we tried to connect in the inject script method (same method as extension) in our mobile wallet.

**Comment by twhy** [comment]
@soaryong-c  If you remove the `wallet-connect` folder, you CAN'T connect to Cosmostation Mobile through WalletConnect.  It that what you want ?

For `inject script`, do you mean you make `window.cosmostation` available in the WebView of Cosmostation Mobile App ?
If that was the case, please take a look at what I did for Leap Mobile
https://github.com/cosmology-tech/cosmos-kit/pull/255/files

The Leap team make `window.leap` available in the WebView of Leap Mobile App and they also set `LeapCosmos` in their userAgent string.
```
Mozilla/5.0 (Linux; Android 11; sdk_gphone_arm64 Build/RSR1.210722.002; wv) 
AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36 LeapCosmos/0.9.5
```

**Comment by soaryong-c** [comment]
@twhy @liujun93 
ok i will try it 
thank you!!!

**Pull request closed without merging**
